version: "3"
services: 
  web:
    container_name: ui-metis
    image: user-interface-metis
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "5000:5000"    
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo-metis
    image: mongo
    ports:
      - "27017:27017"
