version: "3"
services: 
  web:
    container_name: metis-ui
    image: user-interface-metis
    build:
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "50000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://10.20.20.98/
      - ORCHESTRATOR_URL=http://83.212.238.166:50001/analysis
      - NODE_ENV=production
    command: node app.js
