version: "3"
services: 
  web:
    container_name: metis-ui
    image: user-interface-metis
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "5000:5000"    
    volumes:
      - ./:/app:ro
      - /app/node_modules
      - /app/docker/
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/
      - ORCHESTRATOR_URL=http://83.212.238.166:50001/analysis
      - NODE_ENV=development
    command: npm run dev
    restart: always
    depends_on:
      - "mongo"

  mongo:
    container_name: metis-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    restart: always

volumes:
  mongo-db: